name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install flet-cli

      - run: ls -la

      - name: Build APK
        run: flet build apk . --yes --module-name main

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: SmartHome-APK
          path: build/**/*.apk
          if-no-files-found: warn
